---
title: "Categorical  Outcome Training"
author: "Hiroki Matsui"
date: "Thursday, January 15, 2015"
output: html_document
---

## はじめに
この資料は、カテゴリカルアウトカムを解析するうえで医療系で多用されるLogistic Model の使用方法についてRを用いて解説した資料です。  
灰色の枠で囲われた部分がRのコードになっており、Rのコンソールにコピペすることで実行できます。  

## パッケージのインストール
今回使用するパッケージは以下の5つです。

```{r}
install.packages(c("ggplot2","car","GGally","epicalc","pROC"))
```
  
- <a href="http://cran.r-project.org/web/packages/ggplot2/index.html">ggplot2</a>
  極めてメジャーなグラフ描画パッケージ。
  
- <a href = "http://cran.r-project.org/web/packages/car/index.html">car</a>
  "Companion to Applied Regression” という本の内容をパッケージにしたもの。
  
- <a href = "http://cran.r-project.org/web/packages/GGally/index.html">GGally</a>
  ggplot2 の拡張
  
- <a href = "http://cran.r-project.org/web/packages/epicalc/index.html">epicalc</a>
  疫学系の計算パッケージ
  
- <a href = "http://cran.r-project.org/web/packages/pROC/index.html">pROC</a>
  ROC曲線の描画・解析パッケージ


```{r}

library(aod)
library(ggplot2)
library(car)
library(GGally)
library(dplyr)
library(epicalc)
library(Epi)
library(pROC)

```



```{r}
# 元データの読み込み
sample_data <- read.csv("http://www.ats.ucla.edu/stat/data/binary.csv")
#n <- nrow(train_data)
summary(sample_data)
n <- 10000
gpa <- rnorm(n,mean(sample_data$gpa),sd(sample_data$gpa))
gpa <- ifelse(gpa>4,4,gpa)
gpa <- ifelse(gpa<0,0,gpa)
summary(gpa)

hist(sample_data$rank)
rank <- rnorm(n, mean(as.numeric(sample_data$rank))-0.5, sd(as.numeric(sample_data$rank)))
summary(rank)
rank <- cut(rank,breaks = c(min(rank),1,2,3,max(rank)),include.lowest = T,right = T)
rank <- as.numeric(rank)
hist(rank)
rank <- as.factor(rank)

hist(sample_data$gre)
gre <- rnorm(n, mean(as.numeric(sample_data$gre)), sd(as.numeric(sample_data$gre)))
gre <- ifelse(gre>800,800,gre)
gre <- ifelse(gre<0,0,gre)
hist(gre)

train_data <- data.frame(gre = gre, gpa = gpa, rank = rank)


#追加情報を作成
train_data$gre_math <- 0.3 * train_data$gre + rnorm(length(train_data$gre),0,10)
train_data$household <- rlnorm(n,meanlog=5,sdlog=0.4)
hist(train_data$household)
hist(log(train_data$household))
train_data$sex <- ifelse(runif(n = n,0,1)<=0.5,1,0)
#data 特性
#summary(train_data)
#ggpairs(train_data)

# 元のデータの関係をそのままに新しいOutcome Yを作る。
# sampleから係数を算出
sample_data$rank <- factor(sample_data$rank)
samplelogit <- glm(admit ~ gre + gpa + rank, data = sample_data, family = "binomial")
coef_vec <- samplelogit$coefficients

# 係数に基づきYを規定
rank_mat <- model.matrix(~1+ rank,data=train_data)[,-1]
model_df <- cbind(train_data[,colnames(train_data) != "rank"],rank_mat)
model_df$sex_gre <- model_df$sex*model_df$gre
model_df$sex_household <- log(model_df$household)*model_df$gre
head(model_df)
#再設定
summary(model_df)
e <- rlogis(n,0,1)
z <- with(data = model_df,coef_vec[2]*gre + coef_vec[3]*gpa + coef_vec[4]*rank2 + coef_vec[5]*rank3 + coef_vec[6]*rank4
                          -0.35*log(household)+ 0.002*sex_gre +(-2.53) * sex + e)
y_pred <- 1/(1+exp(-z))
hist(y_pred)

train_data$y <- ifelse(y_pred<0.5,1,0)
summary(train_data)
hist(train_data$y)
#head(train_data)
train_data_stock <- train_data
write.csv(train_data,"train_data.csv")



```


```{r}
# Training data の特性をチェック
train_data <- train_data_stock
train_data$y<- as.factor(train_data$y)
train_data$rank<- as.factor(train_data$rank)
train_data$sex <- as.factor(train_data$sex)
summary(train_data)
head(train_data)
ggpairs(train_data)

# イベントごとに因子を確認
filter(train_data, y==1) %>% summary
filter(train_data, y==0) %>% summary

# model構築
# モデル全体の尤度比検定
model <- glm(y ~ 1, data = train_data, family = binomial(logit))
model_0 <- glm(y ~ ., data = train_data, family = binomial(logit))
anova(model,model_0,test= "Chisq")
# 変数の有意差とオッズ比
logistic.display(model_0)
# マルチコチェック
car::vif(model_0)
model_1 <- glm(y ~ gre + gpa + rank + household + sex , data = train_data, family = binomial(logit))
logistic.display(model_1)
anova(model_0,model_1,test= "Chisq")

# 線形性の確認
household_10 <- with(train_data,cut(household,breaks=quantile(x = household,probs = seq(0,1,0.05)),include.lowest = T))
y <- train_data$y
household_10 <- as.numeric(household_10)
p <- apply(table(household_10,y),1,function(x){x[2]/(x[1]+x[2])})
x_3 <- max(household_10)*seq(0,1,0.05)[-1]
plot(x_3,p, main = "x_1 vs Proportion", xlab = "x_1", ylab = "Propotion")
plot(function(x){-log(x)},0,2)

model_2 <- glm(y ~ gre + gpa + rank + log(household) + sex , data = train_data, family = binomial(logit))
logistic.display(model_2)

# 交互作用項の検討
model_3 <- glm(y ~ gre + gpa + rank + log(household) + sex + sex:household, data = train_data, family = binomial(logit))
anova(model_2,model_3,test="Chisq")
logistic.display(model_3)


model_4 <- glm(y ~ gre + gpa + rank + log(household) + sex + sex:gre, data = train_data, family = binomial(logit))
anova(model_2,model_4,test="Chisq")
logistic.display(model_4)

# 交互作用の解釈



```


```{r}
train_data <- train_data_stock
train_data$y<- as.factor(train_data$y)
train_data$rank<- as.factor(train_data$rank)
train_data$sex <- as.factor(train_data$sex)
summary(train_data)
head(train_data)

#train_data
train_data_num <- sample(1:nrow(train_data),size = nrow(train_data)*0.08)
train_data <- train_data[train_data_num,]


model_4 <- glm(y ~ gre+ gre_math + gpa + rank + log(household) + sex + sex:gre + sex:log(household) + rank:gre +rank:log(household), data = train_data, family = binomial(logit))
pred <- predict(model_4,type = "response",newdata = train_data)
hist(pred)
roc_1 <- pROC::roc(response =  as.numeric(train_data$y)-1,predictor =  pred)
pROC::auc(roc_1)
pROC::ci(roc_1)
pROC::coords(roc_1,"best", ret=c("threshold", "specificity", "sensitivity","accuracy","tn", "tp", "fn", "fp", "npv", "ppv", "1-specificity","1-sensitivity", "1-accuracy", "1-npv", "1-ppv"))


model_5 <- glm(y ~ poly(gre,degree = 15)+ gre_math + gpa + rank + poly(log(household),15) + sex + sex:gre + sex:log(household) + rank:gre +rank:log(household) , data = train_data, family = binomial(logit))
pred <- predict(model_5,type = "response",newdata = train_data)
hist(pred)
roc_2 <- pROC::roc(response =  as.numeric(train_data$y)-1,predictor =  pred)
pROC::auc(roc_2)
pROC::ci(roc_2)
pROC::coords(roc_2,"best", ret=c("threshold", "specificity", "sensitivity", "accuracy","tn", "tp", "fn", "fp", "npv", "ppv", "1-specificity",
"1-sensitivity", "1-accuracy", "1-npv", "1-ppv"))

plot(roc_1,col="blue")
plot(roc_2,col="red",add=T)


model_data_num <- sample(1:nrow(train_data),size = nrow(train_data)*0.6)
model_data <- train_data[model_data_num,]
test_data <- train_data[-model_data_num,]



model_6 <- glm(y ~ poly(gre,degree = 15)+ gre_math + gpa + rank + poly(log(household),15) + sex + sex:gre + sex:log(household) + rank:gre +rank:log(household), data = model_data, family = binomial(logit))

pred <- predict(model_6,type = "response",newdata = test_data)
hist(pred)
roc_3 <- pROC::roc(response =  as.numeric(test_data$y)-1,predictor =  pred)
pROC::auc(roc_3)
pROC::ci(roc_3)
pROC::coords(roc_3,"best", ret=c("threshold", "specificity", "sensitivity", "accuracy","tn", "tp", "fn", "fp", "npv", "ppv", "1-specificity",
"1-sensitivity", "1-accuracy", "1-npv", "1-ppv"))


plot(roc_1,col="blue",lty=3)
plot(roc_2,col="blue", add=T)
plot(roc_3,col="red", add=T)

```


### Refernce
http://www.ats.ucla.edu/stat/dae/